name: "Reusable Terraform Apply"

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      state_key:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.DO_SPACES_BUCKET }}" \
            -backend-config="endpoint=sgp1.digitaloceanspaces.com" \
            -backend-config="key=${{ inputs.state_key }}" \
            -backend-config="access_key=${{ secrets.DO_SPACES_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_KEY }}" \
            -backend-config="region=us-east-1" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_region_validation=true"
        working-directory: ${{ inputs.working_directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}

      # Executes the exact plan created during the PR phase
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        working-directory: ${{ inputs.working_directory }}
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}